apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ripple.fullname" . }}
  labels:
    {{- include "ripple.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
