{{- if .Values.gateway.enabled -}}
{{- if .Values.gateway.create -}}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "ripple.fullname" . }}
  labels:
    {{- include "ripple.labels" . | nindent 4 }}
  {{- with .Values.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  gatewayClassName: {{ .Values.gateway.gatewayClassName }}
  listeners:
    {{- range .Values.gateway.listeners }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .port }}
      {{- if .hostname }}
      hostname: {{ .hostname | quote }}
      {{- end }}
      {{- if .tls }}
      tls:
        {{- toYaml .tls | nindent 8 }}
      {{- end }}
      {{- if .allowedRoutes }}
      allowedRoutes:
        {{- toYaml .allowedRoutes | nindent 8 }}
      {{- end }}
    {{- end }}
{{- end }}
{{- end }}
