{{- if .Values.gateway.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "ripple.fullname" . }}
  labels:
    {{- include "ripple.labels" . | nindent 4 }}
  {{- with .Values.gateway.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- if .Values.gateway.create }}
    - name: {{ include "ripple.fullname" . }}
      {{- if .Values.gateway.namespace }}
      namespace: {{ .Values.gateway.namespace }}
      {{- end }}
    {{- else }}
    {{- range .Values.gateway.route.parentRefs }}
    - name: {{ .name }}
      {{- if .namespace }}
      namespace: {{ .namespace }}
      {{- end }}
      {{- if .sectionName }}
      sectionName: {{ .sectionName }}
      {{- end }}
    {{- end }}
    {{- end }}
  {{- if .Values.gateway.route.hostnames }}
  hostnames:
    {{- range .Values.gateway.route.hostnames }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.gateway.route.rules }}
    - {{- if .matches }}
      matches:
        {{- toYaml .matches | nindent 8 }}
      {{- end }}
      {{- if .filters }}
      filters:
        {{- toYaml .filters | nindent 8 }}
      {{- end }}
      backendRefs:
        - name: {{ include "ripple.fullname" $ }}
          port: {{ $.Values.service.port }}
          {{- if .weight }}
          weight: {{ .weight }}
          {{- end }}
    {{- end }}
{{- end }}
